DROP TABLE SELLER_ACCOUNT
DROP TABLE LUNCH
DROP TABLE STOCK
DROP TABLE BBS
DROP TABLE ITEM
DROP TABLE AVATAR
DROP TABLE USER_ACCOUNT
DROP TABLE PRESERVEDAVATAR
DROP TABLE REVIEW
DROP TABLE SALES
DROP TABLE CART
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
